name: Markdown
on:
  push:
    branches: [main]
    paths:
      - "**.md"
      - .github/workflows/markdown.yml
  pull_request:
    paths:
      - "**.md"
      - .github/workflows/markdown.yml

jobs:
  markdown:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: "**.md"
          config: .github/workflows/.markdownlint.json

      - uses: reviewdog/action-misspell@v1
        with:
          locale: "US"
          level: error
          pattern: |
            *.md

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes

      - uses: peter-evans/dockerhub-description@v3
        if: github.repository == 'qdm12/cli-template' && github.event_name == 'push'
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: qmcgaw/cli-template
          short-description: SHORT_DESCRIPTION
          readme-filepath: README.md
